// ============================================================
// SP Smart — IFB Signaling Service
// ============================================================
// Routes WebRTC signaling messages between the Mobile App and
// the Studio Desktop (acting as a pure relay — never touches SDP).
//
// ──  Negotiation flow ────────────────────────────────────────
//
//   Mobile                   Server               Studio
//     │                        │                    │
//     │── CLIENT_IFB_REQUEST ──▶│                    │
//     │   (SDP Offer)           │── REPORTER_OFFER ──▶│
//     │                        │                    │ (creates SDP answer)
//     │                        │◀─ STUDIO_IFB_ANSWER ─│
//     │◀── SERVER_IFB_ANSWER ──│                    │
//     │                        │                    │
//     │ ICE candidates flow bidirectionally as they │
//     │ are generated by both sides.                │
//     │                        │                    │
// ─────────────────────────────────────────────────────────────
//
// The server does NOT interpret SDP content — it only routes it.
// This keeps the signaling server protocol-agnostic and compatible
// with any WebRTC implementation on either side.
// ============================================================

import type { WebSocket } from 'ws';
import { reporterRegistry } from './ReporterRegistry';
import { studioRegistry } from './StudioRegistry';
import { logger } from '../utils/logger';
import type { RTCIceCandidateInit } from '../types/protocol';

// ── Pending ICE candidate queues ─────────────────────────────
// If ICE candidates arrive before the answer is set, we queue them.
// This handles race conditions in the signaling flow.
const pendingMobileIce   = new Map<string, RTCIceCandidateInit[]>(); // reporterId → candidates
const pendingStudioIce   = new Map<string, RTCIceCandidateInit[]>(); // reporterId → candidates

// ── Relay helpers ─────────────────────────────────────────────

function sendToWs(ws: WebSocket, payload: object): void {
  if (ws.readyState !== 1 /* OPEN */) return;
  try {
    ws.send(JSON.stringify(payload));
  } catch (e) {
    logger.error({ e }, '[IFBSignaling] Failed to send WS message');
  }
}

// ─────────────────────────────────────────────────────────────
// Mobile → Studio routing
// ─────────────────────────────────────────────────────────────

/**
 * Called when a mobile reporter sends its SDP offer.
 * Routes to the connected Studio Desktop.
 */
export function onMobileIFBRequest(reporterId: string, sdpOffer: string): void {
  const reporter = reporterRegistry.get(reporterId);
  const studio   = studioRegistry.getPrimary();

  if (!reporter) {
    logger.warn({ reporterId }, '[IFBSignaling] IFB request from unknown reporter');
    return;
  }

  if (!studio) {
    logger.warn({ reporterId }, '[IFBSignaling] No Studio connected — IFB request dropped');
    // Notify the mobile that no studio is available
    sendToWs(reporter.ws, {
      type:      'SERVER_IFB_HANGUP',
      reporterId,
      reason:    'NO_STUDIO_CONNECTED',
    });
    return;
  }

  logger.info({ reporterId, studioId: studio.studioId }, '[IFBSignaling] Routing SDP offer → Studio');

  // Drain any previously queued ICE candidates that arrived early
  const queued = pendingMobileIce.get(reporterId) ?? [];
  pendingMobileIce.delete(reporterId);

  sendToWs(studio.ws, {
    type:        'SERVER_REPORTER_OFFER',
    reporterId,
    displayName: reporter.displayName,
    sdpOffer,
  });

  // Forward queued ICE candidates
  for (const candidate of queued) {
    sendToWs(studio.ws, {
      type:      'SERVER_REPORTER_ICE',
      reporterId,
      candidate,
    });
  }
}

/**
 * Called when a mobile reports an ICE candidate.
 * Routes to the Studio, or queues if no Studio is connected yet.
 */
export function onMobileICECandidate(
  reporterId: string,
  candidate: RTCIceCandidateInit,
): void {
  const studio = studioRegistry.getPrimary();

  if (!studio) {
    // Queue for when Studio connects / offer is sent
    const q = pendingMobileIce.get(reporterId) ?? [];
    q.push(candidate);
    pendingMobileIce.set(reporterId, q);
    return;
  }

  sendToWs(studio.ws, {
    type: 'SERVER_REPORTER_ICE',
    reporterId,
    candidate,
  });
}

// ─────────────────────────────────────────────────────────────
// Studio → Mobile routing
// ─────────────────────────────────────────────────────────────

/**
 * Called when the Studio sends its SDP answer.
 * Routes to the target reporter mobile.
 */
export function onStudioIFBAnswer(
  targetReporterId: string,
  sdpAnswer: string,
): void {
  const reporter = reporterRegistry.get(targetReporterId);

  if (!reporter) {
    logger.warn({ targetReporterId }, '[IFBSignaling] SDP answer for unknown reporter');
    return;
  }

  logger.info({ targetReporterId }, '[IFBSignaling] Routing SDP answer → Mobile');

  sendToWs(reporter.ws, {
    type:       'SERVER_IFB_ANSWER',
    reporterId: targetReporterId,
    sdpAnswer,
  });

  // Drain queued ICE candidates from Studio side
  const queued = pendingStudioIce.get(targetReporterId) ?? [];
  pendingStudioIce.delete(targetReporterId);
  for (const candidate of queued) {
    sendToWs(reporter.ws, {
      type:      'SERVER_ICE_CANDIDATE',
      reporterId: targetReporterId,
      candidate,
      sessionType: 'ifb',
    });
  }
}

/**
 * Called when the Studio sends an ICE candidate for a reporter.
 * Routes to the target reporter, or queues if answer not sent yet.
 */
export function onStudioICECandidate(
  targetReporterId: string,
  candidate: RTCIceCandidateInit,
): void {
  const reporter = reporterRegistry.get(targetReporterId);

  if (!reporter) {
    const q = pendingStudioIce.get(targetReporterId) ?? [];
    q.push(candidate);
    pendingStudioIce.set(targetReporterId, q);
    return;
  }

  sendToWs(reporter.ws, {
    type:        'SERVER_ICE_CANDIDATE',
    reporterId:  targetReporterId,
    candidate,
    sessionType: 'ifb',
  });
}

/**
 * Called when Studio initiates IFB push (Studio-driven, push mode).
 */
export function onStudioIFBOffer(
  targetReporterId: string,
  sdpOffer: string,
): void {
  const reporter = reporterRegistry.get(targetReporterId);

  if (!reporter) {
    logger.warn({ targetReporterId }, '[IFBSignaling] Studio offer for unknown reporter');
    return;
  }

  // In push mode, the server sends SERVER_IFB_ANSWER-compatible message
  // but with an offer — the mobile will create the answer.
  // We reuse SERVER_IFB_ANSWER with sdpAnswer containing the offer SDP.
  // (Clients detect the direction via SDP type field inside the payload.)
  sendToWs(reporter.ws, {
    type:       'SERVER_IFB_ANSWER',
    reporterId: targetReporterId,
    sdpAnswer:  sdpOffer, // Mobile sees offer type in the SDP body
  });
}

/**
 * Called when Studio hangs up IFB for a reporter.
 */
export function onStudioIFBHangup(targetReporterId: string, reason?: string): void {
  const reporter = reporterRegistry.get(targetReporterId);
  if (!reporter) return;

  // Clean up queued candidates
  pendingMobileIce.delete(targetReporterId);
  pendingStudioIce.delete(targetReporterId);

  sendToWs(reporter.ws, {
    type:      'SERVER_IFB_HANGUP',
    reporterId: targetReporterId,
    reason,
  });

  logger.info({ targetReporterId, reason }, '[IFBSignaling] IFB hung up by Studio');
}

/**
 * Called when a reporter disconnects — notifies Studio.
 */
export function onReporterDisconnected(reporterId: string, displayName: string): void {
  const studio = studioRegistry.getPrimary();
  if (!studio) return;

  // Clean queued ICE candidates
  pendingMobileIce.delete(reporterId);
  pendingStudioIce.delete(reporterId);

  sendToWs(studio.ws, {
    type:        'SERVER_REPORTER_LEFT',
    reporterId,
    displayName,
  });
}

export const ifbSignalingService = {
  onMobileIFBRequest,
  onMobileICECandidate,
  onStudioIFBAnswer,
  onStudioICECandidate,
  onStudioIFBOffer,
  onStudioIFBHangup,
  onReporterDisconnected,
};
